name: Unit tests
on:
  push:
    branches: [main, next]
  pull_request:
    branches:  [main, next]
jobs:
  # Ruby unit tests
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.1", "3.2", "3.3"]
        include:
          - ruby: "3.0"
            gemfile: dev/gemfiles/ruby-3.0.x.gemfile
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
